### ISSUE TITLE
Add node_modules to .gitignore to reduce repo size

### ISSUE THREAD

**Issue by tonysulfaro** [ChrisNosowsky/weather-app#1]
This looks like an interesting project! Eager to see how it progresses. I noticed you pushed node_modules up to your repo. Consider adding the default node .gitignore file [here ](https://github.com/github/gitignore/blob/master/Node.gitignore)into it.

Related but I would also look into using [yarn ](https://yarnpkg.com/)for managing packages as it has some nice features like parallel downloads that minimize build time!

For linting/code formatting [ESLint ](https://eslint.org/)and [Prettier ](https://prettier.io/)are niceties as well that you can include in your build script

**Comment by ChrisNosowsky** [comment]
Thank you @tonysulfaro!! I have forgot to add gitignore to this project, but for most of my other repos I have the .gitignore set (although I been just creating my own and didn't even know of the template by github so thanks!)

I added the Prettier package and it definitely helps with formatting JS files.
